version: '3.2'

services:
  consul:
    image: consul:latest
    environment:
      - CONSUL_LOCAL_CONFIG={"disable_update_check":true}
      - TZ=America/Sao_Paulo
    entrypoint:
      - consul
      - agent
      - -server
      - -bootstrap
      - -data-dir=/data
      - -bind={{ GetInterfaceIP "eth0" }}
      - -client=0.0.0.0
      - -ui
      - -advertise=192.168.1.169
    deploy:
      mode: global
      placement:
        constraints: [node.role ==  manager]
    networks:
      - rede_proxy
    ports:
      - 8500:8500

  registrator:
    command: -internal=true consul://consul:8500
    image: gliderlabs/registrator:latest
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - rede_proxy

  meusite:
    image: meusite:latest
    ports:
      - 8080:80
#    volumes:
#      - ./nginx:/usr/share/nginx/html/
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - rede_proxy
    deploy:
      replicas: 2
  
#  sigaa:
#    image: sigaa:latest
#    deploy:
#      replicas: 3 - vai ter ter containers do sigaa
#      update_config: .
#      parallelism: 1 - quando houver alguma atualizacao de imagem por exemplo ele vai fazer 1 container por vez
#      delay: 10s - depois de terminar 1 ele começará  o outro em 10s
#      order: start_first - primeiro ele iniciar os containers novos e depois para os antigos
#    ports:
#      - 8180:8180
#    volumes:
#      - type: bind
#        source: /usr/local/sistemas/
#        target: /usr/local/sistemas/
#      - type: bind
#        source: /usr/local/jboss-5.1.0.GA/
#        target: /usr/local/jboss-5.1.0.GA/
#    environment:
#      - TZ=America/Sao_Paulo
#    networks:
#      - rede_proxy
#    deploy:
#      replicas: 1

  haproxy:
    image: haproxy:1.9.11
    ports:
      - 80:80
      - 443:443
      - 8443:8443
    volumes:
      - ./haproxy/:/usr/local/etc/haproxy:ro
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - rede_proxy
  
networks:
  rede_proxy:
    external:
      name: rede_proxy